apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ebgb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ebgb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ebgb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ebgb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ebgb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hkvi-tenant/rhtap-demo-app/hacbs-test-project-ebgb@sha256:086b0cf311b773e153f1001c3014b0b9193628f93c6eb40d2f3473162e5f3e22
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
