apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ebgb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hkvi-tenant/rhtap-demo-app/hacbs-test-project-ebgb@sha256:086b0cf311b773e153f1001c3014b0b9193628f93c6eb40d2f3473162e5f3e22
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
